import type { Creature } from "./types";

// Palettes per element (gradient base, gradient highlight)
const PAL = {
  fire: ["#ff5b3a", "#ffb380"] as [string, string],
  water: ["#1e6fff", "#6ec1ff"] as [string, string],
  plant: ["#1e9e58", "#7cf0a3"] as [string, string],
  thunder: ["#d9a300", "#fff066"] as [string, string],
  shadow: ["#3a1d6b", "#9a6cff"] as [string, string],
  light: ["#c9a04a", "#fff6c2"] as [string, string]
};

/**
 * The Mythara bestiary. 42 original creatures across 6 elements & 5 rarities.
 * Stats balanced by rarity total budget:
 *   common 150 | rare 220 | epic 310 | legendary 420 | mythic 560
 */
export const CREATURES: Creature[] = [
  // ----- FIRE -----
  { id: "flamlet", name: "Flamlet", element: "fire", rarity: "common",
    hp: 45, atk: 38, def: 28, spd: 39, emoji: "🔥", palette: PAL.fire,
    flavor: "Petite flamme espiègle née d'une braise oubliée.",
    ability: { name: "Étincelle", power: 22, description: "Une vive étincelle qui brûle la cible." } },
  { id: "ashpup", name: "Ashpup", element: "fire", rarity: "common",
    hp: 50, atk: 35, def: 32, spd: 33, emoji: "🐕‍🦺", palette: PAL.fire,
    flavor: "Chiot de cendre fidèle aux gardiens du volcan.",
    ability: { name: "Morsure ardente", power: 20, description: "Mordille en laissant une marque rougeoyante." } },
  { id: "pyrelyn", name: "Pyrelyn", element: "fire", rarity: "rare",
    hp: 65, atk: 58, def: 42, spd: 55, emoji: "🦊", palette: PAL.fire,
    flavor: "Renarde aux queues incandescentes, vive comme la mèche.",
    ability: { name: "Queues brûlantes", power: 35, description: "Frappe répétée à la vitesse du feu." } },
  { id: "magcrab", name: "Magcrab", element: "fire", rarity: "rare",
    hp: 78, atk: 52, def: 56, spd: 34, emoji: "🦀", palette: PAL.fire,
    flavor: "Crustacé volcanique cuirassé de basalte fondu.",
    ability: { name: "Pince fondue", power: 32, description: "Une pince chauffée à blanc qui perce les armures." } },
  { id: "infernyx", name: "Infernyx", element: "fire", rarity: "epic",
    hp: 95, atk: 80, def: 60, spd: 75, emoji: "🐉", palette: PAL.fire,
    flavor: "Drake mineur dont le rugissement allume les forêts.",
    ability: { name: "Souffle infernal", power: 55, description: "Cône de feu qui dévore tout sur son passage." } },
  { id: "solarith", name: "Solarith", element: "fire", rarity: "legendary",
    hp: 120, atk: 110, def: 90, spd: 100, emoji: "☀️", palette: PAL.fire,
    flavor: "Phénix solaire renaissant à chaque aube.",
    ability: { name: "Aube renaissante", power: 80, description: "Embrasement total qui régénère ses forces." } },
  { id: "ignirok", name: "Ignirok le Brasier", element: "fire", rarity: "mythic",
    hp: 160, atk: 145, def: 115, spd: 140, emoji: "🌋", palette: PAL.fire,
    flavor: "Titan volcanique. La terre tremble quand il marche.",
    ability: { name: "Cataclysme", power: 130, description: "Éruption mythique qui ravage le champ de bataille." } },

  // ----- WATER -----
  { id: "tadrop", name: "Tadrop", element: "water", rarity: "common",
    hp: 50, atk: 32, def: 33, spd: 35, emoji: "💧", palette: PAL.water,
    flavor: "Goutte vivante issue d'une source pure.",
    ability: { name: "Bulle", power: 20, description: "Une bulle pressurisée qui éclate sur la cible." } },
  { id: "kelpel", name: "Kelpel", element: "water", rarity: "common",
    hp: 55, atk: 30, def: 38, spd: 27, emoji: "🐢", palette: PAL.water,
    flavor: "Tortillon des récifs. Mange des algues toute la journée.",
    ability: { name: "Carapace algueuse", power: 18, description: "Charge protégée par la mousse marine." } },
  { id: "frostfin", name: "Frostfin", element: "water", rarity: "rare",
    hp: 70, atk: 55, def: 50, spd: 45, emoji: "🐟", palette: PAL.water,
    flavor: "Poisson glacial des abysses du nord.",
    ability: { name: "Lame givrée", power: 33, description: "Frappe avec une nageoire affûtée par le gel." } },
  { id: "mariken", name: "Mariken", element: "water", rarity: "rare",
    hp: 75, atk: 50, def: 45, spd: 50, emoji: "🦑", palette: PAL.water,
    flavor: "Céphalopode rusé et imprévisible.",
    ability: { name: "Encre piégée", power: 30, description: "Aveugle l'adversaire et frappe dans la confusion." } },
  { id: "abysseth", name: "Abysseth", element: "water", rarity: "epic",
    hp: 100, atk: 70, def: 80, spd: 60, emoji: "🐋", palette: PAL.water,
    flavor: "Léviathan des fonds, dont le chant brise les coques.",
    ability: { name: "Chant abyssal", power: 52, description: "Onde sonore dévastatrice à travers l'océan." } },
  { id: "tidequeen", name: "Tidequeen", element: "water", rarity: "legendary",
    hp: 130, atk: 95, def: 105, spd: 90, emoji: "🌊", palette: PAL.water,
    flavor: "Souveraine des marées, elle commande les courants.",
    ability: { name: "Tempête majeure", power: 78, description: "Vague colossale qui balaie les ennemis." } },
  { id: "nereon", name: "Néréon l'Éternel", element: "water", rarity: "mythic",
    hp: 165, atk: 130, def: 140, spd: 125, emoji: "🔱", palette: PAL.water,
    flavor: "Dieu des océans avant les océans.",
    ability: { name: "Déluge primordial", power: 125, description: "Submerge le monde l'espace d'un instant." } },

  // ----- PLANT -----
  { id: "sproutkin", name: "Sproutkin", element: "plant", rarity: "common",
    hp: 52, atk: 30, def: 38, spd: 30, emoji: "🌱", palette: PAL.plant,
    flavor: "Pousse rieuse qui pointe au premier rayon.",
    ability: { name: "Vrille", power: 19, description: "Une liane qui frappe en s'enroulant." } },
  { id: "mossky", name: "Mossky", element: "plant", rarity: "common",
    hp: 48, atk: 33, def: 35, spd: 34, emoji: "🍀", palette: PAL.plant,
    flavor: "Petit lutin de mousse, porte chance, dit-on.",
    ability: { name: "Pollen joyeux", power: 21, description: "Un nuage doré aux effets imprévisibles." } },
  { id: "verdyl", name: "Verdyl", element: "plant", rarity: "rare",
    hp: 72, atk: 52, def: 50, spd: 46, emoji: "🌳", palette: PAL.plant,
    flavor: "Arbuste mobile et farouche.",
    ability: { name: "Branches fouettantes", power: 32, description: "Volée rapide de branches élastiques." } },
  { id: "bloomara", name: "Bloomara", element: "plant", rarity: "rare",
    hp: 68, atk: 56, def: 44, spd: 52, emoji: "🌸", palette: PAL.plant,
    flavor: "Sylphide florale aux pétales tranchants.",
    ability: { name: "Pétales lames", power: 34, description: "Tourbillon de pétales aiguisés." } },
  { id: "sylvaroth", name: "Sylvaroth", element: "plant", rarity: "epic",
    hp: 105, atk: 70, def: 85, spd: 50, emoji: "🌲", palette: PAL.plant,
    flavor: "Ancien gardien sylvestre. Ses racines courent à des lieues.",
    ability: { name: "Étreinte des racines", power: 50, description: "Emprisonne et écrase l'adversaire." } },
  { id: "floraegis", name: "Floraegis", element: "plant", rarity: "legendary",
    hp: 135, atk: 100, def: 110, spd: 75, emoji: "🌺", palette: PAL.plant,
    flavor: "Bouclier vivant de la forêt-mère.",
    ability: { name: "Floraison vorace", power: 76, description: "Fleurs carnivores qui drainent la cible." } },
  { id: "yggdros", name: "Yggdros le Premier", element: "plant", rarity: "mythic",
    hp: 175, atk: 125, def: 150, spd: 110, emoji: "🌳", palette: PAL.plant,
    flavor: "Arbre-monde dont les feuilles racontent l'histoire.",
    ability: { name: "Renaissance sylvestre", power: 122, description: "La forêt entière frappe en un seul coup." } },

  // ----- THUNDER -----
  { id: "voltik", name: "Voltik", element: "thunder", rarity: "common",
    hp: 42, atk: 36, def: 25, spd: 47, emoji: "⚡", palette: PAL.thunder,
    flavor: "Petite foudre vivante. Crépite à chaque pas.",
    ability: { name: "Décharge", power: 23, description: "Saute sur la cible en lâchant un éclair." } },
  { id: "buzzwing", name: "Buzzwing", element: "thunder", rarity: "common",
    hp: 45, atk: 35, def: 28, spd: 42, emoji: "🐝", palette: PAL.thunder,
    flavor: "Insecte chargé, son bourdonnement fait grésiller l'air.",
    ability: { name: "Dard électrique", power: 22, description: "Un dard chargé qui paralyse parfois." } },
  { id: "stormlynx", name: "Stormlynx", element: "thunder", rarity: "rare",
    hp: 60, atk: 60, def: 40, spd: 60, emoji: "🐈‍⬛", palette: PAL.thunder,
    flavor: "Félin véloce, son pelage attire les éclairs.",
    ability: { name: "Bond foudroyant", power: 36, description: "Bond ultra-rapide chargé d'électricité." } },
  { id: "amperox", name: "Amperox", element: "thunder", rarity: "rare",
    hp: 70, atk: 55, def: 50, spd: 45, emoji: "🐂", palette: PAL.thunder,
    flavor: "Bête à cornes en arc voltaïque. Charge mortelle.",
    ability: { name: "Charge orageuse", power: 33, description: "Coup de cornes électrisé." } },
  { id: "tempestral", name: "Tempestral", element: "thunder", rarity: "epic",
    hp: 95, atk: 82, def: 58, spd: 75, emoji: "🦅", palette: PAL.thunder,
    flavor: "Aigle des tempêtes. On l'entend avant de le voir.",
    ability: { name: "Cyclone sismique", power: 54, description: "Bourrasque éclair qui désoriente." } },
  { id: "thunderon", name: "Thunderon", element: "thunder", rarity: "legendary",
    hp: 115, atk: 115, def: 90, spd: 100, emoji: "🐎", palette: PAL.thunder,
    flavor: "Coursier céleste qui brise le mur du tonnerre.",
    ability: { name: "Galop fulgurant", power: 82, description: "Charge à la vitesse de la foudre." } },
  { id: "raitanos", name: "Raïtanos l'Éclair", element: "thunder", rarity: "mythic",
    hp: 150, atk: 155, def: 110, spd: 145, emoji: "⚡", palette: PAL.thunder,
    flavor: "Le tonnerre lui obéit. Le ciel le craint.",
    ability: { name: "Jugement céleste", power: 135, description: "Éclair myhtique tombant du néant." } },

  // ----- SHADOW -----
  { id: "umbril", name: "Umbril", element: "shadow", rarity: "common",
    hp: 46, atk: 36, def: 30, spd: 38, emoji: "👻", palette: PAL.shadow,
    flavor: "Petit fantôme curieux des coins sombres.",
    ability: { name: "Frisson", power: 22, description: "Touche glaciale qui secoue l'âme." } },
  { id: "nyxia", name: "Nyxia", element: "shadow", rarity: "common",
    hp: 44, atk: 38, def: 28, spd: 40, emoji: "🦇", palette: PAL.shadow,
    flavor: "Chauve-souris noire. Murmure des secrets oubliés.",
    ability: { name: "Murmure", power: 21, description: "Effraie la cible et grignote son courage." } },
  { id: "voidkin", name: "Voidkin", element: "shadow", rarity: "rare",
    hp: 65, atk: 60, def: 42, spd: 53, emoji: "🕷️", palette: PAL.shadow,
    flavor: "Araignée des recoins du néant.",
    ability: { name: "Toile abyssale", power: 35, description: "Filaments noirs qui drainent l'énergie." } },
  { id: "shadowmer", name: "Shadowmer", element: "shadow", rarity: "rare",
    hp: 70, atk: 56, def: 50, spd: 44, emoji: "🐺", palette: PAL.shadow,
    flavor: "Loup d'ombre. Apparaît juste avant la nuit.",
    ability: { name: "Croc d'ombre", power: 32, description: "Mordille avec des crocs spectraux." } },
  { id: "eclypsis", name: "Eclypsis", element: "shadow", rarity: "epic",
    hp: 100, atk: 78, def: 65, spd: 67, emoji: "🌑", palette: PAL.shadow,
    flavor: "Manifestation d'une éclipse oubliée.",
    ability: { name: "Voile noir", power: 53, description: "Couvre le champ d'ombres percutantes." } },
  { id: "umbralord", name: "Umbralord", element: "shadow", rarity: "legendary",
    hp: 125, atk: 110, def: 95, spd: 90, emoji: "🦇", palette: PAL.shadow,
    flavor: "Seigneur de la pénombre, juge des âmes errantes.",
    ability: { name: "Sentence sépulcrale", power: 80, description: "Lame d'ombre qui frappe l'esprit." } },
  { id: "noxian", name: "Noxian le Vide", element: "shadow", rarity: "mythic",
    hp: 155, atk: 145, def: 125, spd: 135, emoji: "🕳️", palette: PAL.shadow,
    flavor: "Né du néant entre deux étoiles mortes.",
    ability: { name: "Annihilation", power: 128, description: "Aspire la cible dans le vide absolu." } },

  // ----- LIGHT -----
  { id: "lumelle", name: "Lumelle", element: "light", rarity: "common",
    hp: 48, atk: 33, def: 36, spd: 33, emoji: "✨", palette: PAL.light,
    flavor: "Lucioles divines tournoyant au crépuscule.",
    ability: { name: "Scintillement", power: 21, description: "Éblouit avant de frapper." } },
  { id: "haloo", name: "Haloo", element: "light", rarity: "common",
    hp: 52, atk: 30, def: 38, spd: 30, emoji: "🪽", palette: PAL.light,
    flavor: "Petit chérubin maladroit mais courageux.",
    ability: { name: "Plume sacrée", power: 19, description: "Une plume bénie qui soigne les cœurs." } },
  { id: "solith", name: "Solith", element: "light", rarity: "rare",
    hp: 70, atk: 54, def: 48, spd: 48, emoji: "🌞", palette: PAL.light,
    flavor: "Petit soleil ambulant. Dissipe la peur.",
    ability: { name: "Rayon solaire", power: 33, description: "Faisceau lumineux concentré." } },
  { id: "auralune", name: "Auralune", element: "light", rarity: "rare",
    hp: 65, atk: 52, def: 50, spd: 53, emoji: "🌙", palette: PAL.light,
    flavor: "Esprit lunaire calme et bienveillant.",
    ability: { name: "Croissant", power: 31, description: "Lame de lune qui frappe en silence." } },
  { id: "radience", name: "Radience", element: "light", rarity: "epic",
    hp: 100, atk: 75, def: 75, spd: 60, emoji: "🌟", palette: PAL.light,
    flavor: "Étoile vivante. Sa simple présence redonne espoir.",
    ability: { name: "Aurore éclatante", power: 52, description: "Salve de lumière purifiante." } },
  { id: "celestyx", name: "Celestyx", element: "light", rarity: "legendary",
    hp: 130, atk: 100, def: 110, spd: 80, emoji: "👼", palette: PAL.light,
    flavor: "Ange-veilleur des âges anciens.",
    ability: { name: "Verdict céleste", power: 78, description: "Jugement de lumière implacable." } },
  { id: "auralis", name: "Auralis l'Éveil", element: "light", rarity: "mythic",
    hp: 170, atk: 135, def: 140, spd: 115, emoji: "🌅", palette: PAL.light,
    flavor: "Première lumière qui chassa la première nuit.",
    ability: { name: "Genèse lumineuse", power: 130, description: "Refait briller le monde, brûle l'obscurité." } }
];

export const CREATURES_BY_ID: Record<string, Creature> = Object.fromEntries(
  CREATURES.map((c) => [c.id, c])
);
